version: '3'

services:

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - 1516:80
    depends_on:
      - web
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - '2006:3306'
    environment:
       MYSQL_DATABASE: 'test'
       MYSQL_ROOT: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
     # - ./dump.sql:/docker-entrypoint-initdb.d/dump_b.sql
    restart: always
    networks:
      - app


  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    volumes:
      - .:/DjangoProject
    command: "gunicorn DjangoProject.wsgi:application --bind 0.0.0.0:8080"
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080
    networks:
      - app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge

volumes:
  data:
