# Generated by Django 4.1.1 on 2024-12-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_user_managers_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='notificationcategory',
            table='notification_category',
        ),
        migrations.AlterModelTable(
            name='notificationtemplate',
            table='notification_template',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='translationstring',
            table='translation_string',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usernotification',
            table='user_notification',
        ),
        migrations.AlterModelTable(
            name='usernotificationoption',
            table='user_notification_option',
        ),
        migrations.AlterModelTable(
            name='usernotificationsetting',
            table='user_notification_setting',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
